# Generated by Django 5.1.6 on 2025-02-08 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deadline', models.DateField(help_text='Date when task should be completed', null=True)),
                ('priority', models.IntegerField(help_text='High to Low numeric priority assigned to task')),
                ('name', models.CharField(help_text='Name given to the task', max_length=50)),
                ('text', models.TextField(help_text='Text description of task to be performed')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
